---
- name: Read messages from a kafka topic and act on them
  hosts: all
  ## Define our source for events
  sources:
    - ansible.eda.kafka:
        host: "10.74.128.140"
        port: 9092
        topic: demo
        group_id:

  ## Define the conditions we are looking for
  rules:
    - name: Say Hello
      condition: event.body.i is defined
      ## Define the action we should take should the condition be met
      action:
        debug:
          msg: "{{ event }}"
