---
- name: Hello Events
  hosts: all
  sources:
    - ansible.eda.kafka:
        host: kafka.example.com
        port: 9092
        topic: demo
        group_id:
  rules:
    - name: Say Hello
      condition: event.target_os == "linux"
      action:
        debug:
          msg: "{{ ansible_eda.event }}"
