---
- name: Listen for events on a webhook
  hosts: all
 ## Define our source for events
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
 ## Define the conditions we are looking for
  rules:
    - name: Say Hello
      condition: true
 ## Define the action we should take should the condition be met
      action:
        - name: Print payload debug
          debug:
            msg: "{{ event.payload }}"

      action:
        - name: Print meta debug
          debug:
            msg: "{{ event.payload.meta }}"
